stages:
    - test

tests:
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m doctest -v aspect/action.py
    - python aspect/actionTest.py -v
